config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:index, :create]
    delete 'collaborations/destroy'
  end

  resources :charges, only: [:new, :create]

  resources :downgrades, only: [:new, :create]

  match '/search_suggestions', to: 'search_suggestions#index', via: :get
  
  devise_for :users
  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  attr_writer :all_tags

  belongs_to :user
  has_many :users, through: :collaborations, dependent: :destroy
  has_many :collaborations, dependent: :destroy

  # has_many :taggings, dependent: :destroy
  # has_many :tags, through: :taggings, dependent: :destroy

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :user, presence: true

  after_save :set_tags
  after_create :update_collaboration

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  # Scopes
  default_scope { order('created_at DESC') }
  scope :public_wikis, -> { where(private: false) }

  # Simple methods
  def public?
    private == false
  end

  def collaborators
    users - [user]
  end

  # Tags
  def set_tags
    
    current_tags = self.all_tags.split(",")
    new_tags = @all_tags.split(",")
    
    new_tags.each do |tagg|
      $redis.pipelined do
        $redis.sadd("wiki-#{self.id}",tagg)
        $redis.sadd("tag-#{tagg}",self.id)
      end
    end

    @diff_tags = current_tags - new_tags

    unless @diff_tags.empty?
      @diff_tags.each do |diff|
        $redis.pipelined do
          $redis.srem("tag-#{diff}",self.id)
          $redis.srem("wiki-#{self.id}",diff)
        end
      end
    end


 
  end

  def all_tags
     $redis.smembers("wiki-#{self.id}").join(",")
  end

  def self.search(search)
    if search == ""
      all
    elsif search
        Wiki.where(id: $redis.smembers("tag-#{search}"))
    else
      all
    end
  end

  # Private methods
  private

  def update_collaboration
     Collaboration.create(wiki_id: self.id, user_id: self.user_id)
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @user_wikis = current_user.wikis
    @wikis = Wiki.public_wikis.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
    authorize @wikis
   end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    if request.path != wiki_path(@wiki)
      redirect_to @wiki, status: :moved_permanently
    end
    authorize @wiki    
  end

  def new
    @wiki = Wiki.new
    authorize @wiki    
  end

  def create
    @wiki = Wiki.create(wiki_params)
    @wiki.user_id = current_user.id
    authorize @wiki    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki    
 end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki    
    if @wiki.update_attributes(wiki_params)
      if (@wiki.public? && @wiki.collaborators.any?)
       @wiki.collaborations.each do |collaboration|
         if collaboration.user_id != @wiki.user.id
           collaboration.destroy
         end
      end
    end
     flash[:notice] = "Wiki was updated."
     redirect_to @wiki
    else
      flash[:error] = "There was an error updating the wiki. Please try again."
      render :edit
    end
  end

  def destroy
   @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki    
   if @wiki.destroy
      
      # Remove all tags from redis database
      @wiki.all_tags.split(",").each do |tag|
        $redis.srem("tag-#{tag}",@wiki.id)
      end
      $redis.del("wiki-#{@wiki.id}")
      
      flash[:notice] = "Wiki was deleted successfully."
      redirect_to wikis_path
   else
      flash[:error] = "There was an error deleting the wiki."
      redirect_to wikis_path
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :all_tags)
  end


end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
  <%= form_for wiki do |f| %>
       
    <% if wiki.errors.any? %>
      <div class="alert alert-danger">
      <h4>There are <%= pluralize(wiki.errors.count, "error") %>.</h4>
        <ul>
          <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-group margin-top-20'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.hidden_field :body, id:'body' %>
      <div id="epiceditor"></div>
    </div>
    <% if (policy(wiki)).public_send("#{action}") && current_user.premium? %>
      <div class='form-group'>      
        <%= f.label :private, class: 'checkbox margin-left-13' do %>
          <%= f.check_box :private %> Private Wiki
          <% end %>
      </div>
    <% end %>
    <div class='form-group'>
      <%= f.label "Tags (comma separated)" %>
      <%= f.text_field :all_tags, class: 'form-control', placeholder: "Enter tags separated by commas" %>
    </div>    
      <%= link_to "Cancel", wikis_path, class: "btn btn-danger pull-left" %>
      <%= f.submit "Save", class: 'btn btn-success pull-right', onclick: "prep()" %>
  <% end %>

<script>
   var editor = new EpicEditor().load();
   editor.getElement('editor').body.innerText = '<%= escape_javascript(wiki.body) %>';
   function prep() {
     $("#body")[0].value = editor.getElement('editor').body.innerText;
   }
</script>

app/views/wikis/_wikis.html.erb
<% wikis.each do |wiki| %>
  <tr>
    <td><%= link_to (markdown_to_html wiki.title), wiki %></td>
    <td><%= (wiki.user.username || wiki.user.email) %></td>
    <td class="tdbuttons">
      <% if policy(wiki).edit? %>
        <%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-info'%>
      <% end %>
    </td>
     <td class="tdbuttons">
      <% if policy(wiki).destroy? %>
        <%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger', data: {confirm:'Are you sure you want to delete this wiki?'} %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Edit Wiki</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="pull-right">
      <% if @wiki.private? %>
        <%= link_to "Manage Colaborators", wiki_collaborations_path(@wiki), class: "btn btn-warning pull-right" %>
      <% end %>
    </div>

  <%= render partial: 'form', locals: {wiki: @wiki, action: "destroy?"} %>

<% if @wiki.collaborators.any? %>
  <div class="margin-top-50">
    <small>Collaborating with:
      <ul> 
        <% @wiki.collaborators.each do |collaborator| %>
          <li><%= collaborator.username %></li>
      <% end %>
      </ul>
    </small>
  </div>
<% end %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Wikis</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-right">
    <% if policy(Wiki.new).create? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success pull-right' %>
    <% end %>
    <% if current_user.role == 'standard' %>
      <%= link_to "Upgrade to Premium", new_charge_path, class: 'btn btn-warning pull-left' %>
    <% elsif current_user.role == 'premium' %>
      <%= link_to "Downgrade to Standard", new_downgrade_path, class: 'btn btn-warning pull-left' %>
    <% end %>
  </div>
</div>  

<div class="row margin-top-10">

 <div class="col-md-8" id="public_wikis">
    <table class="table table-striped">
      <th colspan="4" class="text-center">Public wikis</th>
      
      <tr colspan="4">
        <td>
          <%= form_tag wikis_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search], placeholder: "Search by title or tag" %>
            <%= submit_tag "Search", :name => nil %>
          </p>
          <% end %>
        </td>
      </tr>

      <tr class="tr_header">
        <td>Title</td>
        <td>Owner</td>
        <td colspan='2' class="text-center">Actions</td>
      </tr>
        <%= render partial: 'wikis', locals: { wikis: @wikis } %>
    </table>
    <%= will_paginate @wikis %>
  </div>

  <div class="col-md-4" id="my_wikis">
    <table class="table table-striped">
      <th colspan="4" class="text-center">Own/Collaborating wikis</th>
      <tr class="tr_header">
        <td>Title</td>
        <td>Owner</td>
        <td colspan='2' class="text-center">Actions</td>
      </tr>
        <%= render partial: 'wikis', locals: { wikis: @user_wikis } %>
    </table>
  </div>

</div>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">New Wiki</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">

  <%= render partial: 'form', locals: {wiki: @wiki, action: "create?" } %>

  </div>
  <div class="col-md-2"></div>

</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center"><%= markdown_to_html @wiki.title %></h2>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
  </div>

  <div class="col-md-8">
    <div class="margin-top-20 wiki">
      <%= markdown_to_html(@wiki.body) %>
    </div>
    <div class="margin-top-10 tags">
      <strong>Tags: </strong><%= @wiki.all_tags %>
    </div>
    <div class="margin-top-10">
    <%= link_to "Back to Wikis", wikis_path, class: "btn btn-success pull-left" %>
    <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-info pull-right'%>
    </div>
  </div>

  <div class="col-md-2">
  </div>  
</div>

</div>