config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:index, :create]
    delete 'collaborations/destroy'
  end

  resources :charges, only: [:new, :create]

  resources :downgrades, only: [:new, :create]

  match '/search_suggestions', to: 'search_suggestions#index', via: :get
  
  devise_for :users
  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  attr_writer :all_tags

  belongs_to :user
  has_many :users, through: :collaborations, dependent: :destroy
  has_many :collaborations, dependent: :destroy

  # has_many :taggings, dependent: :destroy
  # has_many :tags, through: :taggings, dependent: :destroy

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 20}, presence: true
  validates :user, presence: true

  after_save :set_tags
  after_create :update_collaboration

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end

  # Scopes
  default_scope { order('created_at DESC') }
  scope :public_wikis, -> { where(private: false) }

  # Simple methods
  def public?
    private == false
  end

  def collaborators
    users - [user]
  end

  # Tags
  def set_tags
    
    current_tags = self.all_tags.split(",")
    new_tags = @all_tags.split(",")
    
    new_tags.each do |tagg|
      $redis.pipelined do
        $redis.sadd("wiki-#{self.id}",tagg)
        $redis.sadd("tag-#{tagg}",self.id)
      end
    end

    @diff_tags = current_tags - new_tags

    unless @diff_tags.empty?
      @diff_tags.each do |diff|
        $redis.pipelined do
          $redis.srem("tag-#{diff}",self.id)
          $redis.srem("wiki-#{self.id}",diff)
        end
      end
    end


 
  end

  def all_tags
     $redis.smembers("wiki-#{self.id}").join(",")
  end

  def self.search(search)
    if search == ""
      all
    elsif search
        Wiki.where(id: $redis.smembers("tag-#{search}"))
    else
      all
    end
  end

  # Private methods
  private

  def update_collaboration
     Collaboration.create(wiki_id: self.id, user_id: self.user_id)
  end

end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  
  def index
    @wiki = Wiki.friendly.find(params[:wiki_id])
    @users = User.all - @wiki.users
    @collaborators = @wiki.collaborators
  end

  def create
    @wiki = Wiki.friendly.find(params[:wiki_id])
    @user = User.find_by_name(params[:search])
    if @wiki.users.include? @user 
      flash[:alert] = "User is already collaborating."
      redirect_to wiki_collaborations_path(@wiki)
    elsif @user == nil
      flash[:alert] = "User name does not exist."
      redirect_to wiki_collaborations_path(@wiki)
    else
      flash[:notice] = "Collaborators where updated."
        @collaboration = @wiki.collaborations.create(user_id: @user.id )           
      redirect_to wiki_collaborations_path(@wiki)
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:wiki_id])
    if params[:user_ids]
      flash[:notice] = "Collaborators where updated."
      params[:user_ids].each do |user_id|
          @collaboration = @wiki.collaborations.find_by(user_id: user_id)
          @collaboration.destroy      
      end
      redirect_to wiki_collaborations_path(@wiki)
    else
      flash[:warning] = "No collaborators where removed."
      redirect_to @wiki
    end
  end

end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Add Collaborators</h2>
  </div>
</div>

<div class="row main-collab">

  <div class="col-md-6">
    <h3>Search for Collaborators</h3>
    <%= form_tag wiki_collaborations_path, class: "search-form", :method => :post do %>
      <%= text_field_tag :search, params[:search], class: "search-field", placeholder: "Search by user name" %>
      <%= submit_tag "Add" %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h3>Current Collaborators</h3>
    <%= form_tag wiki_collaborations_destroy_path, :method => :delete do %>
      <% if @collaborators.any? %>
      <div class='form-group collaborators'>      
        <% @collaborators.each do |user| %>
            <%= check_box_tag("user_ids[]", user.id) %>
              <%= label_tag("user_ids[]", (user.name || user.username)) %></br>
        <% end %>
      </div>
        <%= submit_tag "Remove", class: "btn btn-danger" %>
      <% else %>
        None.
      <% end %>
   <% end %>
  </div>

</div>

<div class="row">
    <div class="margin-top-20">
    <%= link_to "Back to Wiki", @wiki, class: "btn btn-info pull-left" %>
  </div>

<script type="text/javascript">
$(function() {
    $( ".search-field" ).autocomplete({
      appendTo: ".search-form",
      source: '/search_suggestions' 
    });
  });
</script>