config/routes.rb
Rails.application.routes.draw do

  resources :wikis do 
    resources :collaborations, only: [:index, :create]
    delete 'collaborations/destroy'
  end

  resources :charges, only: [:new, :create]

  resources :downgrades, only: [:new, :create]

  match '/search_suggestions', to: 'search_suggestions#index', via: :get
  
  devise_for :users
  root 'welcome#index'

end

app/controllers/downgrades_controller.rb
class DowngradesController < ApplicationController

  def new
  end

  def create
    # downgrade role
    current_user.update_attributes(role:'standard')
    
    # change private wikis to public
    private_wikis = current_user.wikis.find_by(private: true)

    if private_wikis
     private_wikis.update_attributes(private: false)
      if private_wikis.collaborations
       private_wikis.collaborations.each do |collaboration|
        if collaboration.user_id != current_user.id
          collaboration.destroy
        end
      end
    end

    end
    
    # refund if applicable
    if current_user.refundable?
      ch = Stripe::Charge.retrieve(current_user.upgrade_charge_id)
      refund = ch.refunds.create
      flash[:alert] = "Your account has been downgraded to standard and a refund has been processed."
    else
      flash[:alert] = "Your account has been downgraded to standard with no refund."
    end
    
    # back to wikis
    redirect_to wikis_path
  end

end

app/helpers/downgrades_helper.rb
module DowngradesHelper
end

app/views/downgrades/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Downgrade to Standard</h2>
  </div>
</div>

<div class="row text-center margin-top-20">
  <p>You have been a Premium user for <%= current_user.upgrade_since_days %> day/s</p>
  <p><strong>Refunds apply if user has been Premium for less than <%= current_user.refund_limit*24 %> hours.</strong></p>
  <%if current_user.refundable? %>
    <%= link_to 'Downgrade & Refund', downgrade_proceed_path, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Downgrade', downgrade_proceed_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/downgrades/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center">Downgrade to Standard</h2>
  </div>
</div>

<div class="row text-center margin-top-20">
  <p>You have been a Premium user for <%= current_user.upgrade_since_days %> day/s</p>
  <p><strong>Refunds apply if user has been Premium for less than <%= current_user.refund_limit*24 %> hours.</strong></p>
  <%if current_user.refundable? %>
    <%= link_to 'Downgrade & Refund', downgrades_path, method: :post, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Downgrade', downgrades_path, method: :post, class: 'btn btn-danger' %>
  <% end %>
</div>